config/routes.rb
Delivr::Application.routes.draw do

  root :to => "home#index"

  # Browsing
  resources :categories do 
    member do
      patch :delete_banner
    end
  end
  resources :items do 
	  resources :item_documents, only: :destroy
	  resources :item_images, only: [:show, :update, :destroy]
	  resources :downloads, only: :destroy
  end
  get 'items/new/:category_id' => 'items#new', as: :new_category_item
  get 'download/:timestamp/:id/:hash.:extension' => 'downloads#download', as: :download_file
  match 'support' => 'home#support', as: :support_form, via: :all

  # Shopping Cart
  post  'cart/add/:id'    => 'cart#add',    as: :add_to_cart
  get   'cart/remove/:id' => 'cart#remove', as: :remove_from_cart
  patch 'cart/update'     => 'cart#update', as: :update_cart
  get   'cart'            => 'cart#view',   as: :view_cart

  get   'checkout' => 'checkout#index', as: :checkout
  match 'checkout/finalize' => 'checkout#finalize', as: :finalize_checkout, via: :all
  get   'checkout/order_confirmation/:id' => 'checkout#order_confirmation', as: :order_confirmation

  # User actions
	match 'auth/:provider/callback', to: 'sessions#create', via: :all
	get   'auth/failure', to: 'sessions#failure'
	get   'signin', to: 'sessions#new', as: 'new_session'
	get   'signout', to: 'sessions#destroy', as: 'signout'
  get   'forgot_password', to: 'sessions#forgot_password'
  post  'forgot_password', to: 'sessions#forgot_password'
  get   'reset_password/:password_reset_digest', to: 'sessions#reset_password', as: :reset_password
  post  'reset_password/:password_reset_digest', to: 'sessions#reset_password'
  patch 'update_password', to: 'profile#update_password'
	get   'my_collection', to: 'profile#show', as: 'profile'
	get   'profile/edit', to: 'profile#edit', as: 'edit_profile'
	patch 'profile/update', to: 'profile#update', as: 'update_profile'
  resources :identities

  get 'sitemap(.:format)' => 'home#sitemap', as: :sitemap, format: :xml
  get 'robots(.:format)'  => 'home#robots',  as: :robots,  format: :text

  # Admin stuff
  get "admin", to: 'admin#index', as: 'admin_root'

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	def index
		# may want to have an actual homepage, if not, jump to the categories
		redirect_to categories_path
	end

	def support
		@support_message = SupportMessage.new
		if request.post?
			safe_params = params.require(:support_message).permit(:name, :email, :subject, :message)
			@support_message = SupportMessage.new(safe_params)
			if @support_message.save
				redirect_to root_path, notice: t('contact_form_success')
			end
		end
	end

  # Generates sitemap.xml
  def sitemap
    @pages = []
    @pages << { 
    	url: root_url,
      updated_at: 1.day.ago,
      changefreq: 'daily',
      priority: 0.7 
    }
    Category.all.each do |category|
    	category.active_items.each do |item|
    		@pages << {
		    	url: url_for(item),
		      updated_at: item.updated_at,
		      changefreq: 'weekly',
		      priority: 0.9 
    		}
    	end
    end
  end

  # Generates robots.txt
  def robots
  end

end

app/views/home/index.html.erb
Welcome to our store.

app/views/home/robots.text.erb
Sitemap: <%= sitemap_url(format: :xml) %>

User-agent: *
Disallow: /cart
Disallow: /download
Disallow: /profile
Disallow: /checkout
Disallow: /auth
Disallow: /signin
Disallow: /signout
Disallow: /forgot_password
Disallow: /reset_password
Disallow: /update_password
Disallow: /my_collection

app/views/home/support.html.erb
<h1 class="text-center"><%= t('contact_us') %></h1>
<% if ENV['SUPPORT_PHONE'] %>
	<p class="text-center"><%= t('call_us') %>: <%= ENV['SUPPORT_PHONE'] %></p>
<% end %>

<div class="row">
	<div class="large-8 large-offset-2 columns">
		<div class="panel">
			<p><%= t('fill_out_the_form_to_contact') %></p>

		<%= simple_form_for @support_message, url: support_form_path do |f| %>

			<%= f.error_notification %>
			<%= f.input :name %>
			<%= f.input :email %>
			<%= f.input :subject %>
			<%= f.input :message, input_html: { style: "height: 150px"} %>

			<br/><%= f.button :submit, class: "radius button" %>
		<% end %>
		</div>
	</div>
</div>