config/routes.rb
Delivr::Application.routes.draw do

  root :to => "home#index"

  # Browsing
  resources :categories do 
    member do
      patch :delete_banner
    end
  end
  resources :items do 
	  resources :item_documents, only: :destroy
	  resources :item_images, only: [:show, :update, :destroy]
	  resources :downloads, only: :destroy
  end
  get 'items/new/:category_id' => 'items#new', as: :new_category_item
  get 'download/:timestamp/:id/:hash.:extension' => 'downloads#download', as: :download_file
  match 'support' => 'home#support', as: :support_form, via: :all

  # Shopping Cart
  post  'cart/add/:id'    => 'cart#add',    as: :add_to_cart
  get   'cart/remove/:id' => 'cart#remove', as: :remove_from_cart
  patch 'cart/update'     => 'cart#update', as: :update_cart
  get   'cart'            => 'cart#view',   as: :view_cart

  get   'checkout' => 'checkout#index', as: :checkout
  match 'checkout/finalize' => 'checkout#finalize', as: :finalize_checkout, via: :all
  get   'checkout/order_confirmation/:id' => 'checkout#order_confirmation', as: :order_confirmation

  # User actions
	match 'auth/:provider/callback', to: 'sessions#create', via: :all
	get   'auth/failure', to: 'sessions#failure'
	get   'signin', to: 'sessions#new', as: 'new_session'
	get   'signout', to: 'sessions#destroy', as: 'signout'
  get   'forgot_password', to: 'sessions#forgot_password'
  post  'forgot_password', to: 'sessions#forgot_password'
  get   'reset_password/:password_reset_digest', to: 'sessions#reset_password', as: :reset_password
  post  'reset_password/:password_reset_digest', to: 'sessions#reset_password'
  patch 'update_password', to: 'profile#update_password'
	get   'my_collection', to: 'profile#show', as: 'profile'
	get   'profile/edit', to: 'profile#edit', as: 'edit_profile'
	patch 'profile/update', to: 'profile#update', as: 'update_profile'
  resources :identities

  get 'sitemap(.:format)' => 'home#sitemap', as: :sitemap, format: :xml
  get 'robots(.:format)'  => 'home#robots',  as: :robots,  format: :text

  # Admin stuff
  get "admin", to: 'admin#index', as: 'admin_root'

end

app/models/item.rb
class Item < ActiveRecord::Base
  extend FriendlyId
  friendly_id :name, use: [:slugged, :finders]
	monetize :price_cents

	has_many :category_items, dependent: :destroy, inverse_of: :item
	has_many :categories, through: :category_items
	has_many :downloads
	has_many :documents, :class_name => "ItemDocument"
	has_many :images, -> { order('position') }, :class_name => "ItemImage"

	validates :name, presence: :true
	validate  :belongs_to_a_category

	accepts_nested_attributes_for :images,    reject_if: :all_blank
	accepts_nested_attributes_for :downloads, reject_if: :all_blank
	accepts_nested_attributes_for :documents, reject_if: :all_blank
	accepts_nested_attributes_for :category_items, reject_if: :all_blank

	after_save :update_category_activations

	def thumbnail
		@thumbnail ||= images.where(role: "thumbnail").first || images.first
	end

	def main_image
		@main_image ||= images.where(role: "main").first || images.first
	end

	def update_category_activations
		categories.each{|c| c.save}
	end

	def belongs_to_a_category
		errors.add(:name, I18n.t('must_belong_to_a_category')) unless categories.size > 0
	end

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :new_item, only: :create
  load_and_authorize_resource

  # GET /items/1
  # GET /items/1.json
  def show
  end

  # GET /items/new
  def new
    if params[:category_id]
      @item.categories << Category.find(params[:category_id])
    end
    build_child_object(3)
  end

  # GET /items/1/edit
  def edit
    build_child_object(2)
  end

  # POST /items
  # POST /items.json
  def create
    respond_to do |format|
      if @item.save
        format.html { redirect_to @item, notice: "#{t('item').capitalize} #{t('was_created')}." }
      else
        build_child_object(3)
        format.html { render action: 'new' }
      end
    end
  end

  # PATCH/PUT /items/1
  # PATCH/PUT /items/1.json
  def update
    respond_to do |format|
      if @item.update!(item_params)
        format.html { redirect_to @item, notice: "#{t('item').capitalize} #{t('was_updated')}." }
      else
        build_child_object(2)
        format.html { render action: 'edit' }
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item.destroy
    respond_to do |format|
      format.html { redirect_to categories_url }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def new_item
      @item = Item.new(item_params)
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def item_params
      params.require(:item).permit(:name, :description, :price, :active, :small_print,
        :category_ids => [], 
        :images_attributes    => [:id, :image], 
        :documents_attributes => [:id, :document], 
        :downloads_attributes => [:id, :name, :file])
    end

    def build_child_object(n=3)
      n.times { @item.images.build }
      (n - 1).times { @item.downloads.build }
      n.times { @item.documents.build }
    end
end

app/views/items/_form.html.erb
<%= simple_form_for(@item, html: { multipart: true }) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <div class="row">
      <div class="large-8 columns">
        <%= f.input :name %>
      </div>
      <div class="large-4 columns">
        <%= f.input :price %>
      </div>
    </div>
    <div class="row">
      <div class="large-4 columns">
        <div class="panel">
          <h5 class="subheader">Images <small>(first pic is main image)</small></h5>
          <%= f.simple_fields_for :images do |im| %>
            <% if im.object.new_record? %>
              <%= im.input :image, label: false %>
            <% else %>
                <%= link_to(image_tag(im.object.image.url(:tiny_square), style: "margin: 0 10px 20px 0"), [@item, im.object]) %>
            <% end %>
          <% end %>
        </div>
      </div>
      <div class="large-4 columns">
        <div class="panel">
          <h5 class="subheader">Documents <small>(public)</small></h5>
          <%= f.simple_fields_for :documents do |doc| %>
            <% if doc.object.new_record? %>
              <%= doc.input :document, label: false %>
            <% else %>
              <p>
                <%= link_to image_tag("trash.gif", alt: "delete"), [@item, doc.object], method: :delete, data: { confirm: "Really?" } %>
                <%= link_to doc.object.document_file_name.truncate(30), doc.object.document.url %>
              </p>
            <% end %>
          <% end %>
        </div>
      </div>
      <div class="large-4 columns">
        <div class="panel">
          <h5 class="subheader">Downloads <small>(private--paid access only)</small></h5>
          <%= f.simple_fields_for :downloads do |d| %>
            <% if d.object.new_record? %>
              <%= d.input :name, label: "Friendly Name" %>
              <%= d.input :file, label: false %><br/>
            <% else %>
              <p>
                <%= link_to image_tag("trash.gif", alt: "delete"), [@item, d.object], method: :delete, data: { confirm: "Really?" } %>
                <%= link_to d.object.name.truncate(30), d.object.file.url %>
              </p>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>
    <p class="hint"><i>Need more attachments? More of each is available each time this item is edited.</i></p>

    <div class="row">
      <div class="large-8 columns">
        <%= f.input :description, input_html: { style: "height: 200px; font-size: 15px"} %>
        <%= f.input :small_print, input_html: { style: "height: 130px; font-size: 12px"}, label: "Small print (compatibility, disclaimer, etc. appears below everything else.)" %>
      </div>
      <div class="large-4 columns">
        <%= f.association :categories, collection: Category.all, as: :check_boxes %>
      </div>
    </div>

    <%= f.input :active %>
    
  </div>

  <div class="form-actions">
    <br/><%= f.button :submit, class: "radius button" %>
  </div>
<% end %>

app/views/items/edit.html.erb
<%= content_for :title do %>Edit: <%= @item.name %><% end %>

<h1>Editing item</h1>

<%= render 'form' %>

app/views/items/new.html.erb
<%= content_for :title do %>New Item<% end %>

<h1>New item</h1>

<%= render 'form' %>

app/views/items/show.html.erb
<%= content_for :title do %><%= @item.name %><% end %>

<div class="row">
	<div class="large-8 columns">
		<h1><%= @item.name %></h1>
	</div>

	<% if can? :manage, @item %>
	<div class="large-4 columns clearfix">
		<br/>
		<ul class="radius button-group right">
			<li><%= link_to t('edit'), edit_item_path(@item), class: 'tiny secondary button' %></li>
			<li><%= link_to t('delete'), @item, class: 'tiny secondary button', method: :delete, data: { confirm: t('confirm_delete') } %></li>
		</ul>
	</div>
	<% end %>
</div>

<div class="row">
	<div class="large-5 large-push-7 small-12 columns">
		<% if @item.main_image %>
		<ul class="clearing-thumbs clearing-feature" data-clearing>
			<li class="clearing-featured-img"><%= link_to(
					interchange_image(@item.main_image, :medium, {
							small: 'small', medium: 'large', large: 'medium'
						}), 
					@item.main_image.image.url ) %></li>
			<% (@item.images - [@item.main_image]).each do |image| %>
				<li><%= link_to image_tag(image.image.url(:thumb)), image.image.url %></li>
			<% end %>
		</ul>
		<% end  %>
		<div class="row">
			<div class="large-10 large-offset-1 columns">
				<% if @item.documents.size > 0 %>
				<h6 class="subheader"><%= t('documentation').capitalize %>:</h6>
				<ul>
					<% @item.documents.each do |d| %>
						<li><%= link_to d.document_file_name.to_s.gsub(/[\\\_\-]/, " "), d.document.url %></li>
					<% end %>
				</ul>
				<% end %>

				<div class="panel text-center">
					<% if current_user && current_user.items.include?(@item) %>
						<%= link_to t('download_now'), quick_item_download_path(@item), class: "medium success radius button" %>
					<% else %>
						<h4 class="subheader">
							<%= humanized_money_with_symbol @item.price %>
						</h4>
						<%= button_to t('add_to_cart'), add_to_cart_path(@item), class: "small radius button" %>
					<% end %>
				</div>
			</div>
		</div>
	</div>
	<div class="large-7 large-pull-5 small-12 columns">
		<div style="margin-bottom: 20px;">
			<%=raw textilize(@item.description) %>

			<div class="small-print"><%=raw textilize(@item.small_print) %></div>
		</div>
	</div>
</div>