config/routes.rb
Delivr::Application.routes.draw do

  root :to => "home#index"

  # Browsing
  resources :categories do 
    member do
      patch :delete_banner
    end
  end
  resources :items do 
	  resources :item_documents, only: :destroy
	  resources :item_images, only: [:show, :update, :destroy]
	  resources :downloads, only: :destroy
  end
  get 'items/new/:category_id' => 'items#new', as: :new_category_item
  get 'download/:timestamp/:id/:hash.:extension' => 'downloads#download', as: :download_file
  match 'support' => 'home#support', as: :support_form, via: :all

  # Shopping Cart
  post  'cart/add/:id'    => 'cart#add',    as: :add_to_cart
  get   'cart/remove/:id' => 'cart#remove', as: :remove_from_cart
  patch 'cart/update'     => 'cart#update', as: :update_cart
  get   'cart'            => 'cart#view',   as: :view_cart

  get   'checkout' => 'checkout#index', as: :checkout
  match 'checkout/finalize' => 'checkout#finalize', as: :finalize_checkout, via: :all
  get   'checkout/order_confirmation/:id' => 'checkout#order_confirmation', as: :order_confirmation

  # User actions
	match 'auth/:provider/callback', to: 'sessions#create', via: :all
	get   'auth/failure', to: 'sessions#failure'
	get   'signin', to: 'sessions#new', as: 'new_session'
	get   'signout', to: 'sessions#destroy', as: 'signout'
  get   'forgot_password', to: 'sessions#forgot_password'
  post  'forgot_password', to: 'sessions#forgot_password'
  get   'reset_password/:password_reset_digest', to: 'sessions#reset_password', as: :reset_password
  post  'reset_password/:password_reset_digest', to: 'sessions#reset_password'
  patch 'update_password', to: 'profile#update_password'
	get   'my_collection', to: 'profile#show', as: 'profile'
	get   'profile/edit', to: 'profile#edit', as: 'edit_profile'
	patch 'profile/update', to: 'profile#update', as: 'update_profile'
  resources :identities

  get 'sitemap(.:format)' => 'home#sitemap', as: :sitemap, format: :xml
  get 'robots(.:format)'  => 'home#robots',  as: :robots,  format: :text

  # Admin stuff
  get "admin", to: 'admin#index', as: 'admin_root'

end

app/models/category.rb
class Category < ActiveRecord::Base
  extend FriendlyId
  friendly_id :name, use: [:slugged, :finders]

	has_many :category_items, dependent: :destroy
	has_many :items, through: :category_items

	validates :name, presence: true

  has_attached_file :header_image, 
    styles: { 
      large_banner:  "1000x200#",
      medium_banner: "800x160#", 
      small_banner:  "400x80#",
      thumb:    "100x100", 
      tiny:     "64x64", 
      tiny_square: "64x64#" 
    }

  validates_attachment_content_type :header_image, content_type: /\Aimage/i

  before_update :count_active_items

  def active_items
  	items.where(active: true)
  end

  def count_active_items
    self.active = active_items.count > 0
    true
  end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :new_category, only: :create
  load_and_authorize_resource

  # GET /categories
  # GET /categories.json
  def index
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  # GET /categories/new
  def new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: "#{category} #{t('was_created')}." }
      else
        format.html { render action: 'new' }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: "#{t('category')} #{t('was_updated')}." }
      else
        format.html { render action: 'edit' }
      end
    end
  end

  def delete_banner
    @category.header_image = nil
    @category.save
    redirect_to edit_category_path(@category)
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def new_category
      @category = Category.new(category_params)
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name, :description, :header_image)
    end
end

app/views/categories/_category.html.erb
<% if category.header_image_file_name.present? %>
  <h1><%= image_tag(category.header_image.url(:large_banner), alt: category.name) %></h1>
<% else %>
  <h1><%= category.name %></h1>
<% end %>

<div class="row clearfix">
  <div class="large-9 columns">
    <%=raw textilize(category.description) %>
  </div>
  <% if can? :manage, category %>
  <div class="large-3 columns clearfix">
    <ul class="radius button-group right">
      <% if can? :create, Item %>
        <li><%= link_to t('add_item'), new_category_item_path(category), class: 'tiny secondary button' %></li>
      <% end %>
      <li><%= link_to t('edit_category'), edit_category_path(category), class: 'tiny secondary button' %></li>
    </ul>
  </div>
  <% end %>
</div>

<ul class="large-block-grid-5 small-block-grid-2">
  <% category.items.accessible_by(current_ability).each do |item| %>
  <li>
    <%= link_to item do %>
      <div class="item-panel" <% if item.thumbnail %>style="background: -moz-linear-gradient(transparent, rgba(0,0,0,1)), url('<%= item.thumbnail.image.url(:medium) %>') 25% -30px no-repeat;"<% end %>>
        <h6><%= item.name %></h6>
      </div>
    <% end %>
  </li>
  <% end %>
</ul>

app/views/categories/_form.html.erb
<%= simple_form_for @category, html: {multipart: true} do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :description, input_html: { style: "height: 120px; font-size: 15px"} %>
    <%= f.input :header_image %>
    <% if @category.header_image.present? %>
    	<p><%= link_to(image_tag(@category.header_image.url(:small_banner)), @category.header_image.url) %>
    	<%= link_to 'delete banner', delete_banner_category_path(@category), method: :patch, data: { confirm: t('confirm_delete')}, class: "tiny radius alert button" %></p>
    <% end %>
  </div>

  <div class="form-actions">
    <br/><%= f.button :submit, class: "radius button" %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<%= content_for :title do %><%= t('edit_category') %><% end %>

<h1><%= t('edit_category') %></h1>

<%= render 'form' %>

<% if can? :destroy, @category %>
<p><%= link_to t('delete'), @category, method: :delete, data: { confirm: t('confirm_delete') }, class: 'tiny alert radius button' %></p>
<% end %>

app/views/categories/index.html.erb
<% if @categories %>
  <%= render :partial => 'category', :collection => @categories %>
<% end %>

app/views/categories/new.html.erb
<%= content_for :title do %><%= t('new_category') %><% end %>

<h1><%= t('new_category') %></h1>

<%= render 'form' %>

app/views/categories/show.html.erb
<%= content_for :title do %><%= @category.name %><% end %>

<%= render @category %>