config/routes.rb
Delivr::Application.routes.draw do

  root :to => "home#index"

  # Browsing
  resources :categories do 
    member do
      patch :delete_banner
    end
  end
  resources :items do 
	  resources :item_documents, only: :destroy
	  resources :item_images, only: [:show, :update, :destroy]
	  resources :downloads, only: :destroy
  end
  get 'items/new/:category_id' => 'items#new', as: :new_category_item
  get 'download/:timestamp/:id/:hash.:extension' => 'downloads#download', as: :download_file
  match 'support' => 'home#support', as: :support_form, via: :all

  # Shopping Cart
  post  'cart/add/:id'    => 'cart#add',    as: :add_to_cart
  get   'cart/remove/:id' => 'cart#remove', as: :remove_from_cart
  patch 'cart/update'     => 'cart#update', as: :update_cart
  get   'cart'            => 'cart#view',   as: :view_cart

  get   'checkout' => 'checkout#index', as: :checkout
  match 'checkout/finalize' => 'checkout#finalize', as: :finalize_checkout, via: :all
  get   'checkout/order_confirmation/:id' => 'checkout#order_confirmation', as: :order_confirmation

  # User actions
	match 'auth/:provider/callback', to: 'sessions#create', via: :all
	get   'auth/failure', to: 'sessions#failure'
	get   'signin', to: 'sessions#new', as: 'new_session'
	get   'signout', to: 'sessions#destroy', as: 'signout'
  get   'forgot_password', to: 'sessions#forgot_password'
  post  'forgot_password', to: 'sessions#forgot_password'
  get   'reset_password/:password_reset_digest', to: 'sessions#reset_password', as: :reset_password
  post  'reset_password/:password_reset_digest', to: 'sessions#reset_password'
  patch 'update_password', to: 'profile#update_password'
	get   'my_collection', to: 'profile#show', as: 'profile'
	get   'profile/edit', to: 'profile#edit', as: 'edit_profile'
	patch 'profile/update', to: 'profile#update', as: 'update_profile'
  resources :identities

  get 'sitemap(.:format)' => 'home#sitemap', as: :sitemap, format: :xml
  get 'robots(.:format)'  => 'home#robots',  as: :robots,  format: :text

  # Admin stuff
  get "admin", to: 'admin#index', as: 'admin_root'

end

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Zurb Foundation %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div data-alert class="alert-box radius <%= name.to_s == 'notice' ? 'success' : 'alert' %>">
      <%= content_tag :div, msg %>
      <a href="#" class="close">&times;</a>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Zurb Foundation 5 %>
<header>
	<div class="sticky">
	<nav class="top-bar" data-topbar>
	  <ul class="title-area">
	    <li class="logo">
	    	<%= link_to root_path, :class => 'brand' do %>
	    		<%= image_tag "logo.png", alt: '' %>
	    		<%= ENV['SITE_NAME'] %>
	    	<% end %>
	    </li>
	    <li class="toggle-topbar menu-icon"><a href="#"><span>Menu</span></a></li>
	  </ul>

	  <div class="top-bar-section">
	  	<ul class="left">
	  		<li><%= link_to t('products'), categories_path %></li>
	  	<% if ENV['SUPPORT_EMAIL'] %>
	  		<li><%= link_to t('contact_us'), support_form_path %></li>
	  	<% elsif ENV['SUPPORT_PHONE'] %>
	  		<li><%= t('contact_us') %>: <%= ENV['SUPPORT_PHONE'] %></li>
	  	<% end %>
	  	</ul>
	  </div>

	  <div class="top-bar-section">
	    <ul class="right">

		<% if session[:cart_id] %>
		  <li><%= link_to t('my_cart'), view_cart_path %></li>
		<% end %>

		<% if user_signed_in? %>
		  <li><%= link_to t('my_collection'), profile_path %></li>
		  <li><%= link_to t('logout'), signout_path %></li>

			<% if current_user.has_role? :admin %>
			   <li class="has-dropdown"><%= link_to t('admin'), admin_root_path %>
			   	  <ul class="dropdown">
			   		<% if can? :create, Category %>
			   			<li><%= link_to t('new_category'), new_category_path %></li>
			   		<% end %>
			   		<% if can? :create, Item %>
			   			<li><%= link_to t('new_item'), new_item_path %></li>
			   		<% end %>
			   	  </ul>
			   </li>
			<% end %>

		<% else %>
		  <li><%= link_to t('login'), new_session_path %></li>
		<% end %>

	    </ul>
	  </div>
	</nav>
	</div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) + " :: " + ENV['SITE_NAME'] : ENV['SITE_NAME'] %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : ENV['SITE_NAME'] %>">
    <%= stylesheet_link_tag "application", media: "all" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= javascript_include_tag "https://js.stripe.com/v1/" %>
    <%= tag :meta, name: "stripe-key", content: ENV['STRIPE_PUBLIC_KEY'] %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <%= render 'layouts/navigation' %>

    <div class="container">
      <div class="row">
        <div class="large-12 columns">
          <%= render 'layouts/messages' %>
          <%= yield %>
        </div>
      </div>
    </div>

    <%= javascript_include_tag "application" %>
    
<% if Rails.env.production? && ENV['GOOGLE_ANALYTICS_ID'] %>
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', '<%= ENV['GOOGLE_ANALYTICS_ID'] %>', 'sonicsprocket.com');
  ga('send', 'pageview');

</script>
<% end %>

  </body>
</html>